PKGDIR		?= ../../../..
L4DIR		?= $(PKGDIR)/../../..

SUBDIRS :=
SRC_CC  := pci-root.cc \
           ec.cc       \
           button.cc   \

REQUIRES_LIBS = acpica

include $(PKGDIR)/server/src/lib_subdir.mk
