PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

SRC_ASSETS_IO	= plat-arm_virt/hw_devices.io \
		  plat-beagleboard/hw_devices.io \
		  plat-exynos5/hw_devices.io \
		  plat-imx6/hw_devices.io \
		  plat-imx8qm/hw_devices.io \
		  plat-msm8916/hw_devices.io \
		  plat-msm8974/hw_devices.io \
		  plat-omap5/hw_devices.io \
		  plat-pandaboard/hw_devices.io \
		  plat-rpi/hw_devices.io \
		  plat-rv/hw_devices.io \
		  plat-rv_pbx/hw_devices.io \
		  plat-rv_vexpress/hw_devices.io \
		  x86-legacy.devs

include $(L4DIR)/mk/assets.mk
